#!/usr/bin/env node

// Creates global logger
const Logger = require('./classes/Logger.js')
global.logger = new Logger(__dirname + '/data/logs/lightkeeper.log', true)

// Creates and launch runner
const Runner = require('./classes/Runner.js')
let runner = new Runner()
runner.runQueue()