#!/usr/bin/env node

// Loads lighthkeeper config
const fs = require('fs');
global.conf = JSON.parse(fs.readFileSync(__dirname + '/conf/lightkeeper.json', 'utf8'));

// Creates global logger
const Logger = require('./classes/Logger.js')
global.logger = new Logger(__dirname + '/data/logs/lightkeeper.log', true)

// Creates and launch runner
const Runner = require('./classes/Runner.js')
let runner = new Runner()
runner.runQueue()